### ISSUE TITLE
Warning: linker: unsopported flags

### ISSUE THREAD

**Issue by ashenzar** [neiviv-ui/termux-sshfs#1]
Thank you for the script! It worked perfectly but when I ran sshfs I got a warning:

#sshfs user@host: mountpoint -o allow_other
WARNING: linker: /data/data/com.termux/files/usr/bin/sshfs: unsupported flags DT_FLAGS_1=0x8000001

After that it works normally but I don't know what it means and sincerely it scares me a little.

**Comment by neiviv-ui** [comment]
> Thank you for the script! It worked perfectly but when I ran sshfs I got a warning:
> 
> #sshfs user@host: mountpoint -o allow_other
> WARNING: linker: /data/data/com.termux/files/usr/bin/sshfs: unsupported flags DT_FLAGS_1=0x8000001
> 
> After that it works normally but I don't know what it means and sincerely it scares me a little.

Thanks,
And don't worry, I already had this error in an emulator (which I didn't have on my tablet) but if seems to be okay (  I have the exact same result on my tab and the emulator)
Bye
edit : it looks like it has already been treated, and that it is a termux specific problem
https://github.com/termux/termux-packages/issues/4894
edit_2 : Never mind, I have corrected it, just run again install.sh script. ^_^
